[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = '192.168.1.113'
port = 3000

[[chains]]
id = 'laozi-mainnet'
rpc_addr =  'http://192.168.1.55:26657'    # 'http://rpc.laozi1.bandchain.org:80'   # 'http://192.168.1.55:26657'
grpc_addr =   'tcp://192.168.1.55:9090'   # 'tcp://rpc.laozi1.bandchain.org:80'  # 'tcp://192.168.1.55:9090'
websocket_addr =   'ws://192.168.1.55:26657/websocket'   # 'http://rpc.laozi1.bandchain.org:80/websocket'    # 'ws://192.168.1.55:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'band'
key_name = 'band'
store_prefix = 'ibc'
#max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.0, denom = 'uband' }
gas_multiplier = 1.2
clock_drift = '895s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['oracle', 'channel-12'], # Desmos
   ['transfer', 'channel-83'], # Osmosis
]

[[chains]]
id = 'desmos-mainnet'
rpc_addr = 'http://192.168.1.35:26657'
grpc_addr = 'tcp://192.168.1.35:9090'
websocket_addr = 'ws://192.168.1.35:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'desmos'
key_name = 'desmos'
store_prefix = 'ibc'
max_gas = 4000000
gas_price = { price = 0.01, denom = 'udsm' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-2'], # Osmosis
   ['ibc-profiles', 'channel-1'], # Band
]

#[[chains]]
#id = 'galaxy-1'
#rpc_addr = 'http://192.168.1.56:27657'
#grpc_addr = 'http://192.168.1.56:9190'
#websocket_addr = 'ws://192.168.1.56:27657/websocket'
#rpc_timeout = '30s'
#account_prefix = 'galaxy'
#key_name = 'galaxy'
#store_prefix = 'ibc'
#max_gas = 1500000
#gas_price = { price = 0.025, denom = 'uglx' }
#gas_multiplier = 1.2
#clock_drift ='20s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
#[chains.packet_filter]
#policy = 'allow'
#list = [
#   ['transfer', 'channel-0'], # osmosis
#]

[[chains]]
id = 'gravity-bridge-3'
rpc_addr = 'http://192.168.1.37:26657'
grpc_addr = 'http://192.168.1.37:9090'
websocket_addr = 'ws://192.168.1.37:26657/websocket'
rpc_timeout = '15s'
account_prefix = 'gravity'
key_name = 'grav'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.0, denom = 'ugraviton' }
gas_multiplier = 1.2
clock_drift ='555s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-7'], # Stargaze
#   ['transfer', 'channel-10'], # Osmosis
   ['transfer', 'channel-53'], # Rizon
   ['transfer', 'channel-83'], # Kujira
]

[[chains]]
id = 'kaiyo-1'
rpc_addr = 'http://192.168.1.250:28657'
grpc_addr =  'tcp://192.168.1.250:9093'
websocket_addr =  'ws://192.168.1.250:28657/websocket'
fee_granter = 'kujira1vkje22mayn72r0a7kna6agv0sqm6k94ry9k6dd'
rpc_timeout = '60s'
account_prefix = 'kujira'
key_name = 'kujira'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.00125, denom = 'ukuji' }
gas_multiplier = 1.2
clock_drift = '5s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-3'], # Osmosis
   ['transfer', 'channel-11'], # Gravity
   ['transfer', 'channel-19'], # Lum
]

[[chains]]
id = 'lum-network-1'
rpc_addr = 'http://192.168.1.116:27657'
grpc_addr = 'http://192.168.1.116:9190'
websocket_addr = 'ws://192.168.1.116:27657/websocket'
rpc_timeout = '15s'
account_prefix = 'lum'
key_name = 'lum'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.001, denom = 'ulum' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-3'], # osmosis
   ['transfer', 'channel-7'], # kujira
]

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://192.168.1.126:26657'
grpc_addr = 'tcp://192.168.1.126:9090'
websocket_addr = 'ws://192.168.1.126:26657/websocket'
rpc_timeout = '30s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 12000000
max_msg_num = 30
gas_price = { price = 0.0025, denom = 'uosmo' }
gas_multiplier = 1.5
max_tx_size = 1800000
clock_drift = '15s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-115'], # Lum
   ['transfer', 'channel-135'], # Desmos
   ['transfer', 'channel-144'], # Gravity
   ['transfer', 'channel-148'], # Band
   ['transfer', 'channel-221'], # Rizon
   ['transfer', 'channel-236'], # Galaxy
   ['transfer', 'channel-259'], # Kujira
   ['transfer', 'channel-362'], # teritori
 ]

[[chains]]
id = 'titan-1'
rpc_addr = 'http://192.168.1.116:26657/'
grpc_addr = 'tcp://192.168.1.116:9090'
websocket_addr = 'ws://192.168.1.116:26657/websocket'
rpc_timeout = '30s'
account_prefix = 'rizon'
key_name = 'rizon'
store_prefix = 'ibc'
max_gas = 6000000
max_msg_num = 10
gas_price = { price = 0.0001, denom = 'uatolo' }
gas_multiplier = 1.2
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # osmosis
   ['transfer', 'channel-4'], #gravity
]

[[chains]]
id = 'teritori-1'
rpc_addr = 'http://192.168.1.152:26657'
grpc_addr = 'http://192.168.1.152:9090'
websocket_addr = 'ws://192.168.1.152:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'tori'
key_name = 'tori'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0, denom = 'utori' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmo
]
