[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = '192.168.1.250'
port = 3000

[[chains]]
id = 'axelar-dojo-1'
rpc_addr = 'http://127.0.0.1:32657'
grpc_addr = 'http://127.0.0.1:9097'
websocket_addr = 'ws://127.0.0.1:32657/websocket'
rpc_timeout = '20s'
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.007, denom = 'uaxl' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-2'], # Cosmos-Hub
   ['transfer', 'channel-3'], # Osmosis
   ['transfer', 'channel-4'], # Juno
   ['transfer', 'channel-6'], # Emoney
   ['transfer', 'channel-14'], # Kujira
   ['transfer', 'channel-18'], # Stargaze
]

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://127.0.0.1:33657'
grpc_addr = 'http://127.0.0.1:9098'
websocket_addr = 'ws://127.0.0.1:33657/websocket'
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.001, denom = 'uatom' }
gas_multiplier = 1.2
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-293'], # Axelar
  ['transfer', 'channel-343'], # Kujira
]

[[chains]]
id = 'emoney-3'
rpc_addr = 'http://127.0.0.1:31657'
grpc_addr = 'tcp://127.0.0.1:9096'
websocket_addr = 'ws://127.0.0.1:31657/websocket'
rpc_timeout = '60s'
account_prefix = 'emoney'
key_name = 'emoney'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.1, denom = 'ungm' }
gas_multiplier = 1.2
clock_drift = '70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmosis
   ['transfer', 'channel-14'],  # Sif
   ['transfer', 'channel-15'],  # Juno
   ['transfer', 'channel-26'],  # Axelar
   ['transfer', 'channel-27'],  # Kujira
 ]
 
 [[chains]]
id = 'juno-1'
rpc_addr = 'http://127.0.0.1:30657'
grpc_addr = 'tcp://127.0.0.1:9095'
websocket_addr = 'ws://127.0.0.1:30657/websocket'
rpc_timeout = '60s'
account_prefix = 'juno'
key_name = 'juno'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.0025, denom = 'ujuno' }
gas_multiplier = 1.2
clock_drift = '895s'
trusting_period = '20days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-5'], # Sifchain
   ['transfer', 'channel-9'], # Emoney
   ['transfer', 'channel-20'], # Stargaze
   ['transfer', 'channel-71'], # Axelar
   ['transfer', 'channel-87'], # Kujira  
   ['wasm.juno1lkv72wruk6m39a2j4ps036hzxyhjccwncgfzzcaqxuwndg5x0ghqa8mrhg', 'channel-97'], # kujira
]

[[chains]]
id = 'kaiyo-1'
rpc_addr = 'http://127.0.0.1:28657'
grpc_addr =  'tcp://127.0.0.1:9093'
websocket_addr =  'ws://127.0.0.1:28657/websocket'
fee_granter = 'kujira1vkje22mayn72r0a7kna6agv0sqm6k94ry9k6dd'
rpc_timeout = '60s'
account_prefix = 'kujira'
key_name = 'kujira'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.00125, denom = 'ukuji' }
gas_multiplier = 1.2
clock_drift = '5s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Cosmos-Hub
   ['transfer', 'channel-1'], # Juno
   ['transfer', 'channel-9'], # Axelar
   ['transfer', 'channel-20'], # Stargaze
   ['transfer', 'channel-21'], # Emoney
   ['transfer', 'channel-31'], # junocw20
]

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'tcp://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'
rpc_timeout = '30s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 6000000
max_msg_num = 10
gas_price = { price = 0.0025 , denom = 'uosmo' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-37'], # Emoney
   ['transfer', 'channel-75'], # Stargaze
   ['transfer', 'channel-208'], # Axelar
 ]
 
 [[chains]]
id = 'sifchain-1'
rpc_addr = 'http://192.168.1.51:26657'
grpc_addr = 'http://192.168.1.51:9090'
websocket_addr = 'ws://192.168.1.51:26657/websocket'
rpc_timeout = '30s'
account_prefix = 'sif'
key_name = 'sif'
store_prefix = 'ibc'
max_gas = 100000000000
gas_price = { price = 20000, denom = 'rowan' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-14'], # Juno
   ['transfer', 'channel-19'], # Emoney
]

[[chains]]
id = 'stargaze-1'
rpc_addr = 'http://127.0.0.1:27657'
grpc_addr = 'tcp://127.0.0.1:9092'
websocket_addr = 'ws://127.0.0.1:27657/websocket'
rpc_timeout = '30s'
account_prefix = 'stars'
key_name = 'stargaze'
store_prefix = 'ibc'
max_gas = 5000000
gas_price = { price = 0.025, denom = 'ustars' }
gas_multiplier = 1.2
clock_drift = '20s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmosis
   ['transfer', 'channel-12'], # Sifchain
   ['transfer', 'channel-5'], # Juno
   ['transfer', 'channel-50'], # Axelar
 ]
