[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = '192.168.1.111'
port = 3000

[[chains]]
id = 'axelar-dojo-1'
rpc_addr = 'http://192.168.1.250:32657'
grpc_addr = 'http://192.168.1.250:9097'
websocket_addr = 'ws://192.168.1.250:32657/websocket'
rpc_timeout = '20s'
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.007, denom = 'uaxl' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-17'], # Ki
   ['transfer', 'channel-21'], # Fetch
   ['transfer', 'channel-32'], # Bitcanna
]

[[chains]]
id = 'bitcanna-1'
rpc_addr = 'http://192.168.1.53:27657' #'https://rpc.bitcanna.io:443'
grpc_addr = 'http://192.168.1.53:9092/' #'https://grpc.bitcanna.io:443'
websocket_addr = 'ws://192.168.1.53:27657/websocket'
rpc_timeout = '20s'
account_prefix = 'bcna'
key_name = 'bcna'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.01, denom = 'ubcna' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '806400s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # osmosis
   ['transfer', 'channel-3'], # cosmos
   ['transfer', 'channel-8'], # gravity
   ['transfer', 'channel-10'], # juno
   ['transfer', 'channel-15'], # axelar
]

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://192.168.1.250:33657'   #'https://rpc-cosmoshub.blockapsis.com:443'   #'http://192.168.1.250:33657'
grpc_addr = 'http://192.168.1.250:9098'
websocket_addr = 'ws://192.168.1.250:33657/websocket'
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.001, denom = 'uatom' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-207'], # Juno
  ['transfer', 'channel-223'], # Kichain
  ['transfer', 'channel-232'], # Bitcanna
  ['transfer', 'channel-277'], # Kava
]

[[chains]]
id = 'fetchhub-4'
rpc_addr = 'http://192.168.1.56:26657/'
grpc_addr = 'tcp://192.168.1.56:9090'
websocket_addr = 'ws://192.168.1.56:26657/websocket'
rpc_timeout = '60s'
account_prefix = 'fetch'
key_name = 'fetch'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 2000000
gas_price = { price = 2, denom = 'afet' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-10'], # Osmosis
   ['transfer', 'channel-14'], # Axelar
]


[[chains]]
id = 'gravity-bridge-3'
rpc_addr = 'http://192.168.1.37:26657'
grpc_addr = 'http://192.168.1.37:9090'
websocket_addr = 'ws://192.168.1.37:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'gravity'
key_name = 'grav'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.0, denom = 'ugraviton' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # Bitcanna
   ['transfer', 'channel-8'], # Juno
   ['transfer', 'channel-37'], # Kichain
]

[[chains]]
id = 'juno-1'
rpc_addr = 'http://192.168.1.250:30657'
grpc_addr = 'tcp://192.168.1.250:9095'
websocket_addr = 'ws://192.168.1.250:30657/websocket'
rpc_timeout = '20s'
account_prefix = 'juno'
key_name = 'juno'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.0025, denom = 'ujuno' }
gas_multiplier = 1.2
clock_drift = '895s'
trusting_period = '20days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmo
   ['transfer', 'channel-1'], # Cosmos
   ['transfer', 'channel-31'], # Gravity
   ['transfer', 'channel-50'], # Bitcanna
   ['transfer', 'channel-58'], # Kichain
   ['wasm.juno1v4887y83d6g28puzvt8cl0f3cdhd3y6y9mpysnsp3k8krdm7l6jqgm0rkn', 'channel-47'], # Osmosis-CW20
]

[[chains]]
id = 'kava_2222-10'
rpc_addr = 'http://192.168.1.54:26657'
grpc_addr = 'tcp://192.168.1.54:9090'
websocket_addr = 'ws://192.168.1.54:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'kava'
key_name = 'kava'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 2000000
gas_price = { price = 0.003, denom = 'ukava' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Cosmos
   ['transfer', 'channel-1'], # Osmosis
]

[[chains]]
id = 'kichain-2'
rpc_addr = 'http://192.168.1.35:27657'
grpc_addr = 'tcp://192.168.1.35:9094'
websocket_addr = 'ws://192.168.1.35:27657/websocket'
rpc_timeout = '20s'
account_prefix = 'ki'
key_name = 'ki'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.025, denom = 'uxki' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmosis
   ['transfer', 'channel-1'], # Cosmos
   ['transfer', 'channel-7'], # Sifchain
   ['transfer', 'channel-8'], # Juno
   ['transfer', 'channel-11'], # Gravity
   ['transfer', 'channel-19'], # Axelar
]

[[chains]]
id = 'osmosis-1'
rpc_addr =  'http://192.168.1.126:26657'
grpc_addr =  'tcp://192.168.1.126:9090'
websocket_addr =  'ws://192.168.1.126:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 120000000
max_msg_num = 30
gas_price = { price = 0.0025, denom = 'uosmo' }
gas_multiplier = 1.2
default_gas = 400000
max_tx_size = 1800000
clock_drift = '5s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-51'], # bitcanna
   ['transfer', 'channel-77'], # kichain
   ['transfer', 'channel-143'], # kava
   ['transfer', 'channel-169'], # Juno CW20
   ['transfer', 'channel-229'], # Fetch
]

[[chains]]
id = 'sifchain-1'
rpc_addr = 'http://192.168.1.51:26657'
grpc_addr = 'http://192.168.1.51:9090'
websocket_addr = 'ws://192.168.1.51:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'sif'
key_name = 'sif'
store_prefix = 'ibc'
max_gas = 1000000000000
gas_price = { price = 20000, denom = 'rowan' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-40'], # kichain
]
